config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers
  end
  root to: "questions#index"
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @question.answers.create(answer_params)
  end
  
  private
  
  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @questions = Question.all
  end
  
  def show
    @answer = @question.answers.build
  end
  
  def new
    @question = Question.new
  end
  
  def edit
  end
  
  def create
    @question = Question.new(question_params)
    
    if @question.save
      redirect_to  @question
    else
      render :new
    end
  end
  
  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end
  
  def destroy
    @question.destroy
    redirect_to questions_path
  end
  
  private
  
  def load_question
    @question = Question.find(params[:id])
  end
  
  def question_params
    params.require(:question).permit(:title, :body)
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/create.js.erb
$('.answers').html('<%= j render 'questions/answers' %>');
$('#answer_body').val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  p= answer.body

app/views/questions/index.html.slim
p = link_to 'Ask question',new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Create'

app/views/questions/show.html.slim
h1 = @question.title
p= @question.body

.answers
  = render 'answers'

= form_for [@question, @answer], remote: true do |f|
  = f.label :body, 'Your answer'
  = f.text_area :body
  = f.submit 'Create'